#!/usr/bin/env bash
#
# This file is part of REANA.
# Copyright (C) 2024 CERN.
#
# REANA is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -o errexit
set -o nounset

check_commitlint () {
    from=${2:-master}
    to=${3:-HEAD}
    pr=${4:-[0-9]+}
    npx commitlint --from="$from" --to="$to"
    found=0
    while IFS= read -r line; do
        commit_hash=$(echo "$line" | cut -d ' ' -f 1)
        commit_title=$(echo "$line" | cut -d ' ' -f 2-)
        commit_number_of_parents=$(git rev-list --parents "$commit_hash" -n1 | awk '{print NF-1}')
        # (i) skip checking release commits generated by Release Please
        if [ "$commit_number_of_parents" -le 1 ] && echo "$commit_title" | grep -qE "^chore\(.*\): release"; then
            continue
        fi
        # (ii) check presence of PR number
        if ! echo "$commit_title" | grep -qE "\(#$pr\)$"; then
            echo "✖   Headline does not end by '(#$pr)' PR number: $commit_title"
            found=1
        fi
        # (iii) check absence of merge commits in feature branches
        if [ "$commit_number_of_parents" -gt 1 ]; then
            if echo "$commit_title" | grep -qE "^chore\(.*\): merge "; then
                break  # skip checking maint-to-master merge commits
            else
                echo "✖   Merge commits are not allowed in feature branches: $commit_title"
                found=1
            fi
        fi
    done < <(git log "$from..$to" --format="%H %s")
    if [ $found -gt 0 ]; then
        exit 1
    fi
}

check_shellcheck () {
    find . -name "*.sh" -exec shellcheck {} \+
}

check_shell_completions () {
    # Check that shell completion files are up-to-date
    go build -o reana-client-go .
    temp_dir=$(mktemp -d)
    trap 'rm -rf "$temp_dir"' EXIT

    ./reana-client-go completion bash > "$temp_dir/reana-client-go"
    ./reana-client-go completion zsh > "$temp_dir/_reana-client-go"

    # Compare bash completion (our header is lines 1-19, Cobra output starts at line 20)
    if ! diff -q <(tail -n +20 etc/bash_completion.d/reana-client-go) "$temp_dir/reana-client-go" > /dev/null 2>&1; then
        echo "✖   Bash completion file is out of date."
        echo "    Please regenerate with: ./reana-client-go completion bash > etc/bash_completion.d/reana-client-go"
        echo "    Then restore the file header."
        exit 1
    fi

    # Compare zsh completion (line 1 is Cobra's #compdef, lines 2-22 are our header, line 23+ is Cobra's line 3+)
    if ! diff -q <(sed -n '1p;23,$p' etc/zsh_completion.d/_reana-client-go) <(sed -n '1p;3,$p' "$temp_dir/_reana-client-go") > /dev/null 2>&1; then
        echo "✖   Zsh completion file is out of date."
        echo "    Please regenerate with: ./reana-client-go completion zsh > etc/zsh_completion.d/_reana-client-go"
        echo "    Then restore the file header."
        exit 1
    fi

    echo "✔   Shell completion files are up-to-date."
}

check_all () {
    check_commitlint
    check_shellcheck
    check_shell_completions
}

if [ $# -eq 0 ]; then
    check_all
    exit 0
fi

arg="$1"
case $arg in
    --check-commitlint) check_commitlint "$@";;
    --check-shellcheck) check_shellcheck;;
    --check-shell-completions) check_shell_completions;;
    *) echo "[ERROR] Invalid argument '$arg'. Exiting." && exit 1;;
esac
