// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BffLogoutReader is a Reader for the BffLogout structure.
type BffLogoutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BffLogoutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewBffLogoutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewBffLogoutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewBffLogoutForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewBffLogoutNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewBffLogoutInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewBffLogoutServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/logout] bff_logout", response, response.Code())
	}
}

// NewBffLogoutOK creates a BffLogoutOK with default headers values
func NewBffLogoutOK() *BffLogoutOK {
	return &BffLogoutOK{}
}

/*
BffLogoutOK describes a response with status code 200, with default header values.

Session ended. The response contains the issuer logout URL.
*/
type BffLogoutOK struct {
	Payload *BffLogoutOKBody
}

// IsSuccess returns true when this bff logout o k response has a 2xx status code
func (o *BffLogoutOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this bff logout o k response has a 3xx status code
func (o *BffLogoutOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bff logout o k response has a 4xx status code
func (o *BffLogoutOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this bff logout o k response has a 5xx status code
func (o *BffLogoutOK) IsServerError() bool {
	return false
}

// IsCode returns true when this bff logout o k response a status code equal to that given
func (o *BffLogoutOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the bff logout o k response
func (o *BffLogoutOK) Code() int {
	return 200
}

func (o *BffLogoutOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/logout][%d] bffLogoutOK %s", 200, payload)
}

func (o *BffLogoutOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/logout][%d] bffLogoutOK %s", 200, payload)
}

func (o *BffLogoutOK) GetPayload() *BffLogoutOKBody {
	return o.Payload
}

func (o *BffLogoutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(BffLogoutOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewBffLogoutUnauthorized creates a BffLogoutUnauthorized with default headers values
func NewBffLogoutUnauthorized() *BffLogoutUnauthorized {
	return &BffLogoutUnauthorized{}
}

/*
BffLogoutUnauthorized describes a response with status code 401, with default header values.

No session cookie present.
*/
type BffLogoutUnauthorized struct {
}

// IsSuccess returns true when this bff logout unauthorized response has a 2xx status code
func (o *BffLogoutUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this bff logout unauthorized response has a 3xx status code
func (o *BffLogoutUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bff logout unauthorized response has a 4xx status code
func (o *BffLogoutUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this bff logout unauthorized response has a 5xx status code
func (o *BffLogoutUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this bff logout unauthorized response a status code equal to that given
func (o *BffLogoutUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the bff logout unauthorized response
func (o *BffLogoutUnauthorized) Code() int {
	return 401
}

func (o *BffLogoutUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/logout][%d] bffLogoutUnauthorized", 401)
}

func (o *BffLogoutUnauthorized) String() string {
	return fmt.Sprintf("[POST /api/logout][%d] bffLogoutUnauthorized", 401)
}

func (o *BffLogoutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewBffLogoutForbidden creates a BffLogoutForbidden with default headers values
func NewBffLogoutForbidden() *BffLogoutForbidden {
	return &BffLogoutForbidden{}
}

/*
BffLogoutForbidden describes a response with status code 403, with default header values.

CSRF validation failed.
*/
type BffLogoutForbidden struct {
}

// IsSuccess returns true when this bff logout forbidden response has a 2xx status code
func (o *BffLogoutForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this bff logout forbidden response has a 3xx status code
func (o *BffLogoutForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bff logout forbidden response has a 4xx status code
func (o *BffLogoutForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this bff logout forbidden response has a 5xx status code
func (o *BffLogoutForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this bff logout forbidden response a status code equal to that given
func (o *BffLogoutForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the bff logout forbidden response
func (o *BffLogoutForbidden) Code() int {
	return 403
}

func (o *BffLogoutForbidden) Error() string {
	return fmt.Sprintf("[POST /api/logout][%d] bffLogoutForbidden", 403)
}

func (o *BffLogoutForbidden) String() string {
	return fmt.Sprintf("[POST /api/logout][%d] bffLogoutForbidden", 403)
}

func (o *BffLogoutForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewBffLogoutNotFound creates a BffLogoutNotFound with default headers values
func NewBffLogoutNotFound() *BffLogoutNotFound {
	return &BffLogoutNotFound{}
}

/*
BffLogoutNotFound describes a response with status code 404, with default header values.

Browser login is not enabled.
*/
type BffLogoutNotFound struct {
}

// IsSuccess returns true when this bff logout not found response has a 2xx status code
func (o *BffLogoutNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this bff logout not found response has a 3xx status code
func (o *BffLogoutNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bff logout not found response has a 4xx status code
func (o *BffLogoutNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this bff logout not found response has a 5xx status code
func (o *BffLogoutNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this bff logout not found response a status code equal to that given
func (o *BffLogoutNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the bff logout not found response
func (o *BffLogoutNotFound) Code() int {
	return 404
}

func (o *BffLogoutNotFound) Error() string {
	return fmt.Sprintf("[POST /api/logout][%d] bffLogoutNotFound", 404)
}

func (o *BffLogoutNotFound) String() string {
	return fmt.Sprintf("[POST /api/logout][%d] bffLogoutNotFound", 404)
}

func (o *BffLogoutNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewBffLogoutInternalServerError creates a BffLogoutInternalServerError with default headers values
func NewBffLogoutInternalServerError() *BffLogoutInternalServerError {
	return &BffLogoutInternalServerError{}
}

/*
BffLogoutInternalServerError describes a response with status code 500, with default header values.

Identity-provider configuration prevents safe session validation. Cookies are preserved so logout can be retried after repair.
*/
type BffLogoutInternalServerError struct {
}

// IsSuccess returns true when this bff logout internal server error response has a 2xx status code
func (o *BffLogoutInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this bff logout internal server error response has a 3xx status code
func (o *BffLogoutInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bff logout internal server error response has a 4xx status code
func (o *BffLogoutInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this bff logout internal server error response has a 5xx status code
func (o *BffLogoutInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this bff logout internal server error response a status code equal to that given
func (o *BffLogoutInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the bff logout internal server error response
func (o *BffLogoutInternalServerError) Code() int {
	return 500
}

func (o *BffLogoutInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/logout][%d] bffLogoutInternalServerError", 500)
}

func (o *BffLogoutInternalServerError) String() string {
	return fmt.Sprintf("[POST /api/logout][%d] bffLogoutInternalServerError", 500)
}

func (o *BffLogoutInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewBffLogoutServiceUnavailable creates a BffLogoutServiceUnavailable with default headers values
func NewBffLogoutServiceUnavailable() *BffLogoutServiceUnavailable {
	return &BffLogoutServiceUnavailable{}
}

/*
BffLogoutServiceUnavailable describes a response with status code 503, with default header values.

Browser session storage or the identity provider is temporarily unavailable. Cookies are preserved so logout can be retried.
*/
type BffLogoutServiceUnavailable struct {
}

// IsSuccess returns true when this bff logout service unavailable response has a 2xx status code
func (o *BffLogoutServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this bff logout service unavailable response has a 3xx status code
func (o *BffLogoutServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bff logout service unavailable response has a 4xx status code
func (o *BffLogoutServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this bff logout service unavailable response has a 5xx status code
func (o *BffLogoutServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this bff logout service unavailable response a status code equal to that given
func (o *BffLogoutServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the bff logout service unavailable response
func (o *BffLogoutServiceUnavailable) Code() int {
	return 503
}

func (o *BffLogoutServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /api/logout][%d] bffLogoutServiceUnavailable", 503)
}

func (o *BffLogoutServiceUnavailable) String() string {
	return fmt.Sprintf("[POST /api/logout][%d] bffLogoutServiceUnavailable", 503)
}

func (o *BffLogoutServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
BffLogoutOKBody bff logout o k body
swagger:model BffLogoutOKBody
*/
type BffLogoutOKBody struct {

	// logout url
	LogoutURL string `json:"logout_url,omitempty"`
}

// Validate validates this bff logout o k body
func (o *BffLogoutOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this bff logout o k body based on context it is used
func (o *BffLogoutOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *BffLogoutOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *BffLogoutOKBody) UnmarshalBinary(b []byte) error {
	var res BffLogoutOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
