// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteGitlabWebhookParams creates a new DeleteGitlabWebhookParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteGitlabWebhookParams() *DeleteGitlabWebhookParams {
	return &DeleteGitlabWebhookParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteGitlabWebhookParamsWithTimeout creates a new DeleteGitlabWebhookParams object
// with the ability to set a timeout on a request.
func NewDeleteGitlabWebhookParamsWithTimeout(timeout time.Duration) *DeleteGitlabWebhookParams {
	return &DeleteGitlabWebhookParams{
		timeout: timeout,
	}
}

// NewDeleteGitlabWebhookParamsWithContext creates a new DeleteGitlabWebhookParams object
// with the ability to set a context for a request.
func NewDeleteGitlabWebhookParamsWithContext(ctx context.Context) *DeleteGitlabWebhookParams {
	return &DeleteGitlabWebhookParams{
		Context: ctx,
	}
}

// NewDeleteGitlabWebhookParamsWithHTTPClient creates a new DeleteGitlabWebhookParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteGitlabWebhookParamsWithHTTPClient(client *http.Client) *DeleteGitlabWebhookParams {
	return &DeleteGitlabWebhookParams{
		HTTPClient: client,
	}
}

/* DeleteGitlabWebhookParams contains all the parameters to send to the API endpoint
   for the delete gitlab webhook operation.

   Typically these are written to a http.Request.
*/
type DeleteGitlabWebhookParams struct {

	/* Data.

	   Data required to delete an existing webhook from GitLab.
	*/
	Data DeleteGitlabWebhookBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete gitlab webhook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteGitlabWebhookParams) WithDefaults() *DeleteGitlabWebhookParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete gitlab webhook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteGitlabWebhookParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete gitlab webhook params
func (o *DeleteGitlabWebhookParams) WithTimeout(timeout time.Duration) *DeleteGitlabWebhookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete gitlab webhook params
func (o *DeleteGitlabWebhookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete gitlab webhook params
func (o *DeleteGitlabWebhookParams) WithContext(ctx context.Context) *DeleteGitlabWebhookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete gitlab webhook params
func (o *DeleteGitlabWebhookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete gitlab webhook params
func (o *DeleteGitlabWebhookParams) WithHTTPClient(client *http.Client) *DeleteGitlabWebhookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete gitlab webhook params
func (o *DeleteGitlabWebhookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the delete gitlab webhook params
func (o *DeleteGitlabWebhookParams) WithData(data DeleteGitlabWebhookBody) *DeleteGitlabWebhookParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the delete gitlab webhook params
func (o *DeleteGitlabWebhookParams) SetData(data DeleteGitlabWebhookBody) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteGitlabWebhookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
