// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteSecretsReader is a Reader for the DeleteSecrets structure.
type DeleteSecretsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSecretsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteSecretsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewDeleteSecretsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteSecretsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteSecretsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteSecretsOK creates a DeleteSecretsOK with default headers values
func NewDeleteSecretsOK() *DeleteSecretsOK {
	return &DeleteSecretsOK{}
}

/* DeleteSecretsOK describes a response with status code 200, with default header values.

Secrets successfully deleted.
*/
type DeleteSecretsOK struct {
	Payload []string
}

func (o *DeleteSecretsOK) Error() string {
	return fmt.Sprintf("[DELETE /api/secrets/][%d] deleteSecretsOK  %+v", 200, o.Payload)
}
func (o *DeleteSecretsOK) GetPayload() []string {
	return o.Payload
}

func (o *DeleteSecretsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSecretsForbidden creates a DeleteSecretsForbidden with default headers values
func NewDeleteSecretsForbidden() *DeleteSecretsForbidden {
	return &DeleteSecretsForbidden{}
}

/* DeleteSecretsForbidden describes a response with status code 403, with default header values.

Request failed. Token is not valid.
*/
type DeleteSecretsForbidden struct {
}

func (o *DeleteSecretsForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/secrets/][%d] deleteSecretsForbidden ", 403)
}

func (o *DeleteSecretsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSecretsNotFound creates a DeleteSecretsNotFound with default headers values
func NewDeleteSecretsNotFound() *DeleteSecretsNotFound {
	return &DeleteSecretsNotFound{}
}

/* DeleteSecretsNotFound describes a response with status code 404, with default header values.

Request failed. Secrets do not exist.
*/
type DeleteSecretsNotFound struct {
	Payload []string
}

func (o *DeleteSecretsNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/secrets/][%d] deleteSecretsNotFound  %+v", 404, o.Payload)
}
func (o *DeleteSecretsNotFound) GetPayload() []string {
	return o.Payload
}

func (o *DeleteSecretsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSecretsInternalServerError creates a DeleteSecretsInternalServerError with default headers values
func NewDeleteSecretsInternalServerError() *DeleteSecretsInternalServerError {
	return &DeleteSecretsInternalServerError{}
}

/* DeleteSecretsInternalServerError describes a response with status code 500, with default header values.

Request failed. Internal server error.
*/
type DeleteSecretsInternalServerError struct {
}

func (o *DeleteSecretsInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /api/secrets/][%d] deleteSecretsInternalServerError ", 500)
}

func (o *DeleteSecretsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
