// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInteractiveSessionSecretParams creates a new GetInteractiveSessionSecretParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInteractiveSessionSecretParams() *GetInteractiveSessionSecretParams {
	return &GetInteractiveSessionSecretParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInteractiveSessionSecretParamsWithTimeout creates a new GetInteractiveSessionSecretParams object
// with the ability to set a timeout on a request.
func NewGetInteractiveSessionSecretParamsWithTimeout(timeout time.Duration) *GetInteractiveSessionSecretParams {
	return &GetInteractiveSessionSecretParams{
		timeout: timeout,
	}
}

// NewGetInteractiveSessionSecretParamsWithContext creates a new GetInteractiveSessionSecretParams object
// with the ability to set a context for a request.
func NewGetInteractiveSessionSecretParamsWithContext(ctx context.Context) *GetInteractiveSessionSecretParams {
	return &GetInteractiveSessionSecretParams{
		Context: ctx,
	}
}

// NewGetInteractiveSessionSecretParamsWithHTTPClient creates a new GetInteractiveSessionSecretParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInteractiveSessionSecretParamsWithHTTPClient(client *http.Client) *GetInteractiveSessionSecretParams {
	return &GetInteractiveSessionSecretParams{
		HTTPClient: client,
	}
}

/*
GetInteractiveSessionSecretParams contains all the parameters to send to the API endpoint

	for the get interactive session secret operation.

	Typically these are written to a http.Request.
*/
type GetInteractiveSessionSecretParams struct {

	/* WorkflowIDOrName.

	   Required. Workflow UUID or name.
	*/
	WorkflowIDOrName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get interactive session secret params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInteractiveSessionSecretParams) WithDefaults() *GetInteractiveSessionSecretParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get interactive session secret params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInteractiveSessionSecretParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get interactive session secret params
func (o *GetInteractiveSessionSecretParams) WithTimeout(timeout time.Duration) *GetInteractiveSessionSecretParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get interactive session secret params
func (o *GetInteractiveSessionSecretParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get interactive session secret params
func (o *GetInteractiveSessionSecretParams) WithContext(ctx context.Context) *GetInteractiveSessionSecretParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get interactive session secret params
func (o *GetInteractiveSessionSecretParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get interactive session secret params
func (o *GetInteractiveSessionSecretParams) WithHTTPClient(client *http.Client) *GetInteractiveSessionSecretParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get interactive session secret params
func (o *GetInteractiveSessionSecretParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWorkflowIDOrName adds the workflowIDOrName to the get interactive session secret params
func (o *GetInteractiveSessionSecretParams) WithWorkflowIDOrName(workflowIDOrName string) *GetInteractiveSessionSecretParams {
	o.SetWorkflowIDOrName(workflowIDOrName)
	return o
}

// SetWorkflowIDOrName adds the workflowIdOrName to the get interactive session secret params
func (o *GetInteractiveSessionSecretParams) SetWorkflowIDOrName(workflowIDOrName string) {
	o.WorkflowIDOrName = workflowIDOrName
}

// WriteToRequest writes these params to a swagger request
func (o *GetInteractiveSessionSecretParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param workflow_id_or_name
	if err := r.SetPathParam("workflow_id_or_name", o.WorkflowIDOrName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
