// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetWorkflowSpecificationParams creates a new GetWorkflowSpecificationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetWorkflowSpecificationParams() *GetWorkflowSpecificationParams {
	return &GetWorkflowSpecificationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetWorkflowSpecificationParamsWithTimeout creates a new GetWorkflowSpecificationParams object
// with the ability to set a timeout on a request.
func NewGetWorkflowSpecificationParamsWithTimeout(timeout time.Duration) *GetWorkflowSpecificationParams {
	return &GetWorkflowSpecificationParams{
		timeout: timeout,
	}
}

// NewGetWorkflowSpecificationParamsWithContext creates a new GetWorkflowSpecificationParams object
// with the ability to set a context for a request.
func NewGetWorkflowSpecificationParamsWithContext(ctx context.Context) *GetWorkflowSpecificationParams {
	return &GetWorkflowSpecificationParams{
		Context: ctx,
	}
}

// NewGetWorkflowSpecificationParamsWithHTTPClient creates a new GetWorkflowSpecificationParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetWorkflowSpecificationParamsWithHTTPClient(client *http.Client) *GetWorkflowSpecificationParams {
	return &GetWorkflowSpecificationParams{
		HTTPClient: client,
	}
}

/*
GetWorkflowSpecificationParams contains all the parameters to send to the API endpoint

	for the get workflow specification operation.

	Typically these are written to a http.Request.
*/
type GetWorkflowSpecificationParams struct {

	/* AccessToken.

	   API access_token of workflow owner.
	*/
	AccessToken *string

	/* WorkflowIDOrName.

	   Required. Analysis UUID or name.
	*/
	WorkflowIDOrName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get workflow specification params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWorkflowSpecificationParams) WithDefaults() *GetWorkflowSpecificationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get workflow specification params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWorkflowSpecificationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get workflow specification params
func (o *GetWorkflowSpecificationParams) WithTimeout(timeout time.Duration) *GetWorkflowSpecificationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get workflow specification params
func (o *GetWorkflowSpecificationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get workflow specification params
func (o *GetWorkflowSpecificationParams) WithContext(ctx context.Context) *GetWorkflowSpecificationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get workflow specification params
func (o *GetWorkflowSpecificationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get workflow specification params
func (o *GetWorkflowSpecificationParams) WithHTTPClient(client *http.Client) *GetWorkflowSpecificationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get workflow specification params
func (o *GetWorkflowSpecificationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccessToken adds the accessToken to the get workflow specification params
func (o *GetWorkflowSpecificationParams) WithAccessToken(accessToken *string) *GetWorkflowSpecificationParams {
	o.SetAccessToken(accessToken)
	return o
}

// SetAccessToken adds the accessToken to the get workflow specification params
func (o *GetWorkflowSpecificationParams) SetAccessToken(accessToken *string) {
	o.AccessToken = accessToken
}

// WithWorkflowIDOrName adds the workflowIDOrName to the get workflow specification params
func (o *GetWorkflowSpecificationParams) WithWorkflowIDOrName(workflowIDOrName string) *GetWorkflowSpecificationParams {
	o.SetWorkflowIDOrName(workflowIDOrName)
	return o
}

// SetWorkflowIDOrName adds the workflowIdOrName to the get workflow specification params
func (o *GetWorkflowSpecificationParams) SetWorkflowIDOrName(workflowIDOrName string) {
	o.WorkflowIDOrName = workflowIDOrName
}

// WriteToRequest writes these params to a swagger request
func (o *GetWorkflowSpecificationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AccessToken != nil {

		// query param access_token
		var qrAccessToken string

		if o.AccessToken != nil {
			qrAccessToken = *o.AccessToken
		}
		qAccessToken := qrAccessToken
		if qAccessToken != "" {

			if err := r.SetQueryParam("access_token", qAccessToken); err != nil {
				return err
			}
		}
	}

	// path param workflow_id_or_name
	if err := r.SetPathParam("workflow_id_or_name", o.WorkflowIDOrName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
