// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HealthReader is a Reader for the Health structure.
type HealthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HealthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewHealthOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewHealthServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/health] health", response, response.Code())
	}
}

// NewHealthOK creates a HealthOK with default headers values
func NewHealthOK() *HealthOK {
	return &HealthOK{}
}

/*
HealthOK describes a response with status code 200, with default header values.

The BFF session store (when configured) is healthy. The issuer check may still be false; that is informational only.
*/
type HealthOK struct {
	Payload *HealthOKBody
}

// IsSuccess returns true when this health o k response has a 2xx status code
func (o *HealthOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this health o k response has a 3xx status code
func (o *HealthOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this health o k response has a 4xx status code
func (o *HealthOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this health o k response has a 5xx status code
func (o *HealthOK) IsServerError() bool {
	return false
}

// IsCode returns true when this health o k response a status code equal to that given
func (o *HealthOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the health o k response
func (o *HealthOK) Code() int {
	return 200
}

func (o *HealthOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/health][%d] healthOK %s", 200, payload)
}

func (o *HealthOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/health][%d] healthOK %s", 200, payload)
}

func (o *HealthOK) GetPayload() *HealthOKBody {
	return o.Payload
}

func (o *HealthOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(HealthOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewHealthServiceUnavailable creates a HealthServiceUnavailable with default headers values
func NewHealthServiceUnavailable() *HealthServiceUnavailable {
	return &HealthServiceUnavailable{}
}

/*
HealthServiceUnavailable describes a response with status code 503, with default header values.

The BFF session store (when configured) is unreachable.
*/
type HealthServiceUnavailable struct {
	Payload *HealthServiceUnavailableBody
}

// IsSuccess returns true when this health service unavailable response has a 2xx status code
func (o *HealthServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this health service unavailable response has a 3xx status code
func (o *HealthServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this health service unavailable response has a 4xx status code
func (o *HealthServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this health service unavailable response has a 5xx status code
func (o *HealthServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this health service unavailable response a status code equal to that given
func (o *HealthServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the health service unavailable response
func (o *HealthServiceUnavailable) Code() int {
	return 503
}

func (o *HealthServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/health][%d] healthServiceUnavailable %s", 503, payload)
}

func (o *HealthServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/health][%d] healthServiceUnavailable %s", 503, payload)
}

func (o *HealthServiceUnavailable) GetPayload() *HealthServiceUnavailableBody {
	return o.Payload
}

func (o *HealthServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(HealthServiceUnavailableBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
HealthOKBody health o k body
swagger:model HealthOKBody
*/
type HealthOKBody struct {

	// checks
	Checks any `json:"checks,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this health o k body
func (o *HealthOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this health o k body based on context it is used
func (o *HealthOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *HealthOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *HealthOKBody) UnmarshalBinary(b []byte) error {
	var res HealthOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
HealthServiceUnavailableBody health service unavailable body
swagger:model HealthServiceUnavailableBody
*/
type HealthServiceUnavailableBody struct {

	// checks
	Checks any `json:"checks,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this health service unavailable body
func (o *HealthServiceUnavailableBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this health service unavailable body based on context it is used
func (o *HealthServiceUnavailableBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *HealthServiceUnavailableBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *HealthServiceUnavailableBody) UnmarshalBinary(b []byte) error {
	var res HealthServiceUnavailableBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
