// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PruneWorkspaceReader is a Reader for the PruneWorkspace structure.
type PruneWorkspaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PruneWorkspaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPruneWorkspaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPruneWorkspaceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPruneWorkspaceForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPruneWorkspaceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPruneWorkspaceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/workflows/{workflow_id_or_name}/prune] prune_workspace", response, response.Code())
	}
}

// NewPruneWorkspaceOK creates a PruneWorkspaceOK with default headers values
func NewPruneWorkspaceOK() *PruneWorkspaceOK {
	return &PruneWorkspaceOK{}
}

/*
PruneWorkspaceOK describes a response with status code 200, with default header values.

Request succeeded. The workspace has been pruned.
*/
type PruneWorkspaceOK struct {
	Payload *PruneWorkspaceOKBody
}

// IsSuccess returns true when this prune workspace o k response has a 2xx status code
func (o *PruneWorkspaceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this prune workspace o k response has a 3xx status code
func (o *PruneWorkspaceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this prune workspace o k response has a 4xx status code
func (o *PruneWorkspaceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this prune workspace o k response has a 5xx status code
func (o *PruneWorkspaceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this prune workspace o k response a status code equal to that given
func (o *PruneWorkspaceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the prune workspace o k response
func (o *PruneWorkspaceOK) Code() int {
	return 200
}

func (o *PruneWorkspaceOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/workflows/{workflow_id_or_name}/prune][%d] pruneWorkspaceOK %s", 200, payload)
}

func (o *PruneWorkspaceOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/workflows/{workflow_id_or_name}/prune][%d] pruneWorkspaceOK %s", 200, payload)
}

func (o *PruneWorkspaceOK) GetPayload() *PruneWorkspaceOKBody {
	return o.Payload
}

func (o *PruneWorkspaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PruneWorkspaceOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPruneWorkspaceBadRequest creates a PruneWorkspaceBadRequest with default headers values
func NewPruneWorkspaceBadRequest() *PruneWorkspaceBadRequest {
	return &PruneWorkspaceBadRequest{}
}

/*
PruneWorkspaceBadRequest describes a response with status code 400, with default header values.

Request failed. The incoming data specification seems malformed.
*/
type PruneWorkspaceBadRequest struct {
	Payload *PruneWorkspaceBadRequestBody
}

// IsSuccess returns true when this prune workspace bad request response has a 2xx status code
func (o *PruneWorkspaceBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this prune workspace bad request response has a 3xx status code
func (o *PruneWorkspaceBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this prune workspace bad request response has a 4xx status code
func (o *PruneWorkspaceBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this prune workspace bad request response has a 5xx status code
func (o *PruneWorkspaceBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this prune workspace bad request response a status code equal to that given
func (o *PruneWorkspaceBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the prune workspace bad request response
func (o *PruneWorkspaceBadRequest) Code() int {
	return 400
}

func (o *PruneWorkspaceBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/workflows/{workflow_id_or_name}/prune][%d] pruneWorkspaceBadRequest %s", 400, payload)
}

func (o *PruneWorkspaceBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/workflows/{workflow_id_or_name}/prune][%d] pruneWorkspaceBadRequest %s", 400, payload)
}

func (o *PruneWorkspaceBadRequest) GetPayload() *PruneWorkspaceBadRequestBody {
	return o.Payload
}

func (o *PruneWorkspaceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PruneWorkspaceBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPruneWorkspaceForbidden creates a PruneWorkspaceForbidden with default headers values
func NewPruneWorkspaceForbidden() *PruneWorkspaceForbidden {
	return &PruneWorkspaceForbidden{}
}

/*
PruneWorkspaceForbidden describes a response with status code 403, with default header values.

Request failed. User is not allowed to access workflow.
*/
type PruneWorkspaceForbidden struct {
	Payload *PruneWorkspaceForbiddenBody
}

// IsSuccess returns true when this prune workspace forbidden response has a 2xx status code
func (o *PruneWorkspaceForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this prune workspace forbidden response has a 3xx status code
func (o *PruneWorkspaceForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this prune workspace forbidden response has a 4xx status code
func (o *PruneWorkspaceForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this prune workspace forbidden response has a 5xx status code
func (o *PruneWorkspaceForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this prune workspace forbidden response a status code equal to that given
func (o *PruneWorkspaceForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the prune workspace forbidden response
func (o *PruneWorkspaceForbidden) Code() int {
	return 403
}

func (o *PruneWorkspaceForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/workflows/{workflow_id_or_name}/prune][%d] pruneWorkspaceForbidden %s", 403, payload)
}

func (o *PruneWorkspaceForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/workflows/{workflow_id_or_name}/prune][%d] pruneWorkspaceForbidden %s", 403, payload)
}

func (o *PruneWorkspaceForbidden) GetPayload() *PruneWorkspaceForbiddenBody {
	return o.Payload
}

func (o *PruneWorkspaceForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PruneWorkspaceForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPruneWorkspaceNotFound creates a PruneWorkspaceNotFound with default headers values
func NewPruneWorkspaceNotFound() *PruneWorkspaceNotFound {
	return &PruneWorkspaceNotFound{}
}

/*
PruneWorkspaceNotFound describes a response with status code 404, with default header values.

Request failed. User does not exist.
*/
type PruneWorkspaceNotFound struct {
	Payload *PruneWorkspaceNotFoundBody
}

// IsSuccess returns true when this prune workspace not found response has a 2xx status code
func (o *PruneWorkspaceNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this prune workspace not found response has a 3xx status code
func (o *PruneWorkspaceNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this prune workspace not found response has a 4xx status code
func (o *PruneWorkspaceNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this prune workspace not found response has a 5xx status code
func (o *PruneWorkspaceNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this prune workspace not found response a status code equal to that given
func (o *PruneWorkspaceNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the prune workspace not found response
func (o *PruneWorkspaceNotFound) Code() int {
	return 404
}

func (o *PruneWorkspaceNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/workflows/{workflow_id_or_name}/prune][%d] pruneWorkspaceNotFound %s", 404, payload)
}

func (o *PruneWorkspaceNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/workflows/{workflow_id_or_name}/prune][%d] pruneWorkspaceNotFound %s", 404, payload)
}

func (o *PruneWorkspaceNotFound) GetPayload() *PruneWorkspaceNotFoundBody {
	return o.Payload
}

func (o *PruneWorkspaceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PruneWorkspaceNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPruneWorkspaceInternalServerError creates a PruneWorkspaceInternalServerError with default headers values
func NewPruneWorkspaceInternalServerError() *PruneWorkspaceInternalServerError {
	return &PruneWorkspaceInternalServerError{}
}

/*
PruneWorkspaceInternalServerError describes a response with status code 500, with default header values.

Request failed. Internal controller error.
*/
type PruneWorkspaceInternalServerError struct {
	Payload *PruneWorkspaceInternalServerErrorBody
}

// IsSuccess returns true when this prune workspace internal server error response has a 2xx status code
func (o *PruneWorkspaceInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this prune workspace internal server error response has a 3xx status code
func (o *PruneWorkspaceInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this prune workspace internal server error response has a 4xx status code
func (o *PruneWorkspaceInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this prune workspace internal server error response has a 5xx status code
func (o *PruneWorkspaceInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this prune workspace internal server error response a status code equal to that given
func (o *PruneWorkspaceInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the prune workspace internal server error response
func (o *PruneWorkspaceInternalServerError) Code() int {
	return 500
}

func (o *PruneWorkspaceInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/workflows/{workflow_id_or_name}/prune][%d] pruneWorkspaceInternalServerError %s", 500, payload)
}

func (o *PruneWorkspaceInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/workflows/{workflow_id_or_name}/prune][%d] pruneWorkspaceInternalServerError %s", 500, payload)
}

func (o *PruneWorkspaceInternalServerError) GetPayload() *PruneWorkspaceInternalServerErrorBody {
	return o.Payload
}

func (o *PruneWorkspaceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PruneWorkspaceInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
PruneWorkspaceBadRequestBody prune workspace bad request body
swagger:model PruneWorkspaceBadRequestBody
*/
type PruneWorkspaceBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this prune workspace bad request body
func (o *PruneWorkspaceBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this prune workspace bad request body based on context it is used
func (o *PruneWorkspaceBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PruneWorkspaceBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PruneWorkspaceBadRequestBody) UnmarshalBinary(b []byte) error {
	var res PruneWorkspaceBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
PruneWorkspaceForbiddenBody prune workspace forbidden body
swagger:model PruneWorkspaceForbiddenBody
*/
type PruneWorkspaceForbiddenBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this prune workspace forbidden body
func (o *PruneWorkspaceForbiddenBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this prune workspace forbidden body based on context it is used
func (o *PruneWorkspaceForbiddenBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PruneWorkspaceForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PruneWorkspaceForbiddenBody) UnmarshalBinary(b []byte) error {
	var res PruneWorkspaceForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
PruneWorkspaceInternalServerErrorBody prune workspace internal server error body
swagger:model PruneWorkspaceInternalServerErrorBody
*/
type PruneWorkspaceInternalServerErrorBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this prune workspace internal server error body
func (o *PruneWorkspaceInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this prune workspace internal server error body based on context it is used
func (o *PruneWorkspaceInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PruneWorkspaceInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PruneWorkspaceInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res PruneWorkspaceInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
PruneWorkspaceNotFoundBody prune workspace not found body
swagger:model PruneWorkspaceNotFoundBody
*/
type PruneWorkspaceNotFoundBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this prune workspace not found body
func (o *PruneWorkspaceNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this prune workspace not found body based on context it is used
func (o *PruneWorkspaceNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PruneWorkspaceNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PruneWorkspaceNotFoundBody) UnmarshalBinary(b []byte) error {
	var res PruneWorkspaceNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
PruneWorkspaceOKBody prune workspace o k body
swagger:model PruneWorkspaceOKBody
*/
type PruneWorkspaceOKBody struct {

	// message
	Message string `json:"message,omitempty"`

	// workflow id
	WorkflowID string `json:"workflow_id,omitempty"`

	// workflow name
	WorkflowName string `json:"workflow_name,omitempty"`
}

// Validate validates this prune workspace o k body
func (o *PruneWorkspaceOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this prune workspace o k body based on context it is used
func (o *PruneWorkspaceOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PruneWorkspaceOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PruneWorkspaceOKBody) UnmarshalBinary(b []byte) error {
	var res PruneWorkspaceOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
