// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPruneWorkspaceParams creates a new PruneWorkspaceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPruneWorkspaceParams() *PruneWorkspaceParams {
	return &PruneWorkspaceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPruneWorkspaceParamsWithTimeout creates a new PruneWorkspaceParams object
// with the ability to set a timeout on a request.
func NewPruneWorkspaceParamsWithTimeout(timeout time.Duration) *PruneWorkspaceParams {
	return &PruneWorkspaceParams{
		timeout: timeout,
	}
}

// NewPruneWorkspaceParamsWithContext creates a new PruneWorkspaceParams object
// with the ability to set a context for a request.
func NewPruneWorkspaceParamsWithContext(ctx context.Context) *PruneWorkspaceParams {
	return &PruneWorkspaceParams{
		Context: ctx,
	}
}

// NewPruneWorkspaceParamsWithHTTPClient creates a new PruneWorkspaceParams object
// with the ability to set a custom HTTPClient for a request.
func NewPruneWorkspaceParamsWithHTTPClient(client *http.Client) *PruneWorkspaceParams {
	return &PruneWorkspaceParams{
		HTTPClient: client,
	}
}

/*
PruneWorkspaceParams contains all the parameters to send to the API endpoint

	for the prune workspace operation.

	Typically these are written to a http.Request.
*/
type PruneWorkspaceParams struct {

	/* AccessToken.

	   The API access_token of workflow owner.
	*/
	AccessToken *string

	/* IncludeInputs.

	   Optional. Delete also the input files of the workflow.
	*/
	IncludeInputs *bool

	/* IncludeOutputs.

	   Optional. Delete also the output files of the workflow.
	*/
	IncludeOutputs *bool

	/* WorkflowIDOrName.

	   Required. Analysis UUID or name.
	*/
	WorkflowIDOrName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the prune workspace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PruneWorkspaceParams) WithDefaults() *PruneWorkspaceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the prune workspace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PruneWorkspaceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the prune workspace params
func (o *PruneWorkspaceParams) WithTimeout(timeout time.Duration) *PruneWorkspaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the prune workspace params
func (o *PruneWorkspaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the prune workspace params
func (o *PruneWorkspaceParams) WithContext(ctx context.Context) *PruneWorkspaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the prune workspace params
func (o *PruneWorkspaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the prune workspace params
func (o *PruneWorkspaceParams) WithHTTPClient(client *http.Client) *PruneWorkspaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the prune workspace params
func (o *PruneWorkspaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccessToken adds the accessToken to the prune workspace params
func (o *PruneWorkspaceParams) WithAccessToken(accessToken *string) *PruneWorkspaceParams {
	o.SetAccessToken(accessToken)
	return o
}

// SetAccessToken adds the accessToken to the prune workspace params
func (o *PruneWorkspaceParams) SetAccessToken(accessToken *string) {
	o.AccessToken = accessToken
}

// WithIncludeInputs adds the includeInputs to the prune workspace params
func (o *PruneWorkspaceParams) WithIncludeInputs(includeInputs *bool) *PruneWorkspaceParams {
	o.SetIncludeInputs(includeInputs)
	return o
}

// SetIncludeInputs adds the includeInputs to the prune workspace params
func (o *PruneWorkspaceParams) SetIncludeInputs(includeInputs *bool) {
	o.IncludeInputs = includeInputs
}

// WithIncludeOutputs adds the includeOutputs to the prune workspace params
func (o *PruneWorkspaceParams) WithIncludeOutputs(includeOutputs *bool) *PruneWorkspaceParams {
	o.SetIncludeOutputs(includeOutputs)
	return o
}

// SetIncludeOutputs adds the includeOutputs to the prune workspace params
func (o *PruneWorkspaceParams) SetIncludeOutputs(includeOutputs *bool) {
	o.IncludeOutputs = includeOutputs
}

// WithWorkflowIDOrName adds the workflowIDOrName to the prune workspace params
func (o *PruneWorkspaceParams) WithWorkflowIDOrName(workflowIDOrName string) *PruneWorkspaceParams {
	o.SetWorkflowIDOrName(workflowIDOrName)
	return o
}

// SetWorkflowIDOrName adds the workflowIdOrName to the prune workspace params
func (o *PruneWorkspaceParams) SetWorkflowIDOrName(workflowIDOrName string) {
	o.WorkflowIDOrName = workflowIDOrName
}

// WriteToRequest writes these params to a swagger request
func (o *PruneWorkspaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AccessToken != nil {

		// query param access_token
		var qrAccessToken string

		if o.AccessToken != nil {
			qrAccessToken = *o.AccessToken
		}
		qAccessToken := qrAccessToken
		if qAccessToken != "" {

			if err := r.SetQueryParam("access_token", qAccessToken); err != nil {
				return err
			}
		}
	}

	if o.IncludeInputs != nil {

		// query param include_inputs
		var qrIncludeInputs bool

		if o.IncludeInputs != nil {
			qrIncludeInputs = *o.IncludeInputs
		}
		qIncludeInputs := swag.FormatBool(qrIncludeInputs)
		if qIncludeInputs != "" {

			if err := r.SetQueryParam("include_inputs", qIncludeInputs); err != nil {
				return err
			}
		}
	}

	if o.IncludeOutputs != nil {

		// query param include_outputs
		var qrIncludeOutputs bool

		if o.IncludeOutputs != nil {
			qrIncludeOutputs = *o.IncludeOutputs
		}
		qIncludeOutputs := swag.FormatBool(qrIncludeOutputs)
		if qIncludeOutputs != "" {

			if err := r.SetQueryParam("include_outputs", qIncludeOutputs); err != nil {
				return err
			}
		}
	}

	// path param workflow_id_or_name
	if err := r.SetPathParam("workflow_id_or_name", o.WorkflowIDOrName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
