// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRenewGitlabWebhookTokenParams creates a new RenewGitlabWebhookTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRenewGitlabWebhookTokenParams() *RenewGitlabWebhookTokenParams {
	return &RenewGitlabWebhookTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRenewGitlabWebhookTokenParamsWithTimeout creates a new RenewGitlabWebhookTokenParams object
// with the ability to set a timeout on a request.
func NewRenewGitlabWebhookTokenParamsWithTimeout(timeout time.Duration) *RenewGitlabWebhookTokenParams {
	return &RenewGitlabWebhookTokenParams{
		timeout: timeout,
	}
}

// NewRenewGitlabWebhookTokenParamsWithContext creates a new RenewGitlabWebhookTokenParams object
// with the ability to set a context for a request.
func NewRenewGitlabWebhookTokenParamsWithContext(ctx context.Context) *RenewGitlabWebhookTokenParams {
	return &RenewGitlabWebhookTokenParams{
		Context: ctx,
	}
}

// NewRenewGitlabWebhookTokenParamsWithHTTPClient creates a new RenewGitlabWebhookTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewRenewGitlabWebhookTokenParamsWithHTTPClient(client *http.Client) *RenewGitlabWebhookTokenParams {
	return &RenewGitlabWebhookTokenParams{
		HTTPClient: client,
	}
}

/*
RenewGitlabWebhookTokenParams contains all the parameters to send to the API endpoint

	for the renew gitlab webhook token operation.

	Typically these are written to a http.Request.
*/
type RenewGitlabWebhookTokenParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the renew gitlab webhook token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RenewGitlabWebhookTokenParams) WithDefaults() *RenewGitlabWebhookTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the renew gitlab webhook token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RenewGitlabWebhookTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the renew gitlab webhook token params
func (o *RenewGitlabWebhookTokenParams) WithTimeout(timeout time.Duration) *RenewGitlabWebhookTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the renew gitlab webhook token params
func (o *RenewGitlabWebhookTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the renew gitlab webhook token params
func (o *RenewGitlabWebhookTokenParams) WithContext(ctx context.Context) *RenewGitlabWebhookTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the renew gitlab webhook token params
func (o *RenewGitlabWebhookTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the renew gitlab webhook token params
func (o *RenewGitlabWebhookTokenParams) WithHTTPClient(client *http.Client) *RenewGitlabWebhookTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the renew gitlab webhook token params
func (o *RenewGitlabWebhookTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *RenewGitlabWebhookTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
