// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUnshareWorkflowParams creates a new UnshareWorkflowParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUnshareWorkflowParams() *UnshareWorkflowParams {
	return &UnshareWorkflowParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUnshareWorkflowParamsWithTimeout creates a new UnshareWorkflowParams object
// with the ability to set a timeout on a request.
func NewUnshareWorkflowParamsWithTimeout(timeout time.Duration) *UnshareWorkflowParams {
	return &UnshareWorkflowParams{
		timeout: timeout,
	}
}

// NewUnshareWorkflowParamsWithContext creates a new UnshareWorkflowParams object
// with the ability to set a context for a request.
func NewUnshareWorkflowParamsWithContext(ctx context.Context) *UnshareWorkflowParams {
	return &UnshareWorkflowParams{
		Context: ctx,
	}
}

// NewUnshareWorkflowParamsWithHTTPClient creates a new UnshareWorkflowParams object
// with the ability to set a custom HTTPClient for a request.
func NewUnshareWorkflowParamsWithHTTPClient(client *http.Client) *UnshareWorkflowParams {
	return &UnshareWorkflowParams{
		HTTPClient: client,
	}
}

/*
UnshareWorkflowParams contains all the parameters to send to the API endpoint

	for the unshare workflow operation.

	Typically these are written to a http.Request.
*/
type UnshareWorkflowParams struct {

	/* AccessToken.

	   The API access_token of workflow owner.
	*/
	AccessToken *string

	/* UserEmailToUnshareWith.

	   Required. User to unshare the workflow with.
	*/
	UserEmailToUnshareWith string

	/* WorkflowIDOrName.

	   Required. Workflow UUID or name.
	*/
	WorkflowIDOrName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the unshare workflow params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UnshareWorkflowParams) WithDefaults() *UnshareWorkflowParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the unshare workflow params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UnshareWorkflowParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the unshare workflow params
func (o *UnshareWorkflowParams) WithTimeout(timeout time.Duration) *UnshareWorkflowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the unshare workflow params
func (o *UnshareWorkflowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the unshare workflow params
func (o *UnshareWorkflowParams) WithContext(ctx context.Context) *UnshareWorkflowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the unshare workflow params
func (o *UnshareWorkflowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the unshare workflow params
func (o *UnshareWorkflowParams) WithHTTPClient(client *http.Client) *UnshareWorkflowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the unshare workflow params
func (o *UnshareWorkflowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccessToken adds the accessToken to the unshare workflow params
func (o *UnshareWorkflowParams) WithAccessToken(accessToken *string) *UnshareWorkflowParams {
	o.SetAccessToken(accessToken)
	return o
}

// SetAccessToken adds the accessToken to the unshare workflow params
func (o *UnshareWorkflowParams) SetAccessToken(accessToken *string) {
	o.AccessToken = accessToken
}

// WithUserEmailToUnshareWith adds the userEmailToUnshareWith to the unshare workflow params
func (o *UnshareWorkflowParams) WithUserEmailToUnshareWith(userEmailToUnshareWith string) *UnshareWorkflowParams {
	o.SetUserEmailToUnshareWith(userEmailToUnshareWith)
	return o
}

// SetUserEmailToUnshareWith adds the userEmailToUnshareWith to the unshare workflow params
func (o *UnshareWorkflowParams) SetUserEmailToUnshareWith(userEmailToUnshareWith string) {
	o.UserEmailToUnshareWith = userEmailToUnshareWith
}

// WithWorkflowIDOrName adds the workflowIDOrName to the unshare workflow params
func (o *UnshareWorkflowParams) WithWorkflowIDOrName(workflowIDOrName string) *UnshareWorkflowParams {
	o.SetWorkflowIDOrName(workflowIDOrName)
	return o
}

// SetWorkflowIDOrName adds the workflowIdOrName to the unshare workflow params
func (o *UnshareWorkflowParams) SetWorkflowIDOrName(workflowIDOrName string) {
	o.WorkflowIDOrName = workflowIDOrName
}

// WriteToRequest writes these params to a swagger request
func (o *UnshareWorkflowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AccessToken != nil {

		// query param access_token
		var qrAccessToken string

		if o.AccessToken != nil {
			qrAccessToken = *o.AccessToken
		}
		qAccessToken := qrAccessToken
		if qAccessToken != "" {

			if err := r.SetQueryParam("access_token", qAccessToken); err != nil {
				return err
			}
		}
	}

	// query param user_email_to_unshare_with
	qrUserEmailToUnshareWith := o.UserEmailToUnshareWith
	qUserEmailToUnshareWith := qrUserEmailToUnshareWith
	if qUserEmailToUnshareWith != "" {

		if err := r.SetQueryParam("user_email_to_unshare_with", qUserEmailToUnshareWith); err != nil {
			return err
		}
	}

	// path param workflow_id_or_name
	if err := r.SetPathParam("workflow_id_or_name", o.WorkflowIDOrName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
