// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewValidateWorkflowSpecificationParams creates a new ValidateWorkflowSpecificationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewValidateWorkflowSpecificationParams() *ValidateWorkflowSpecificationParams {
	return &ValidateWorkflowSpecificationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewValidateWorkflowSpecificationParamsWithTimeout creates a new ValidateWorkflowSpecificationParams object
// with the ability to set a timeout on a request.
func NewValidateWorkflowSpecificationParamsWithTimeout(timeout time.Duration) *ValidateWorkflowSpecificationParams {
	return &ValidateWorkflowSpecificationParams{
		timeout: timeout,
	}
}

// NewValidateWorkflowSpecificationParamsWithContext creates a new ValidateWorkflowSpecificationParams object
// with the ability to set a context for a request.
func NewValidateWorkflowSpecificationParamsWithContext(ctx context.Context) *ValidateWorkflowSpecificationParams {
	return &ValidateWorkflowSpecificationParams{
		Context: ctx,
	}
}

// NewValidateWorkflowSpecificationParamsWithHTTPClient creates a new ValidateWorkflowSpecificationParams object
// with the ability to set a custom HTTPClient for a request.
func NewValidateWorkflowSpecificationParamsWithHTTPClient(client *http.Client) *ValidateWorkflowSpecificationParams {
	return &ValidateWorkflowSpecificationParams{
		HTTPClient: client,
	}
}

/*
ValidateWorkflowSpecificationParams contains all the parameters to send to the API endpoint

	for the validate workflow specification operation.

	Typically these are written to a http.Request.
*/
type ValidateWorkflowSpecificationParams struct {

	/* Bundle.

	   Uncompressed ZIP validation snapshot containing canonical reana.yaml plus explicitly declared workflow sources.
	*/
	Bundle runtime.NamedReadCloser

	/* Environments.

	   If true, run offline reproducibility checks on runtime environment image references and return the loaded image and effective runtime UID/GID combinations so the client can optionally pull and inspect them locally.
	*/
	Environments *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the validate workflow specification params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ValidateWorkflowSpecificationParams) WithDefaults() *ValidateWorkflowSpecificationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the validate workflow specification params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ValidateWorkflowSpecificationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the validate workflow specification params
func (o *ValidateWorkflowSpecificationParams) WithTimeout(timeout time.Duration) *ValidateWorkflowSpecificationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the validate workflow specification params
func (o *ValidateWorkflowSpecificationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the validate workflow specification params
func (o *ValidateWorkflowSpecificationParams) WithContext(ctx context.Context) *ValidateWorkflowSpecificationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the validate workflow specification params
func (o *ValidateWorkflowSpecificationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the validate workflow specification params
func (o *ValidateWorkflowSpecificationParams) WithHTTPClient(client *http.Client) *ValidateWorkflowSpecificationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the validate workflow specification params
func (o *ValidateWorkflowSpecificationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBundle adds the bundle to the validate workflow specification params
func (o *ValidateWorkflowSpecificationParams) WithBundle(bundle runtime.NamedReadCloser) *ValidateWorkflowSpecificationParams {
	o.SetBundle(bundle)
	return o
}

// SetBundle adds the bundle to the validate workflow specification params
func (o *ValidateWorkflowSpecificationParams) SetBundle(bundle runtime.NamedReadCloser) {
	o.Bundle = bundle
}

// WithEnvironments adds the environments to the validate workflow specification params
func (o *ValidateWorkflowSpecificationParams) WithEnvironments(environments *bool) *ValidateWorkflowSpecificationParams {
	o.SetEnvironments(environments)
	return o
}

// SetEnvironments adds the environments to the validate workflow specification params
func (o *ValidateWorkflowSpecificationParams) SetEnvironments(environments *bool) {
	o.Environments = environments
}

// WriteToRequest writes these params to a swagger request
func (o *ValidateWorkflowSpecificationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	// form file param bundle
	if err := r.SetFileParam("bundle", o.Bundle); err != nil {
		return err
	}

	if o.Environments != nil {

		// query param environments
		var qrEnvironments bool

		if o.Environments != nil {
			qrEnvironments = *o.Environments
		}
		qEnvironments := swag.FormatBool(qrEnvironments)
		if qEnvironments != "" {

			if err := r.SetQueryParam("environments", qEnvironments); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
